### PR TITLE
Add BitSlider demo page (#711)

### LINKED ISSUE #711: Add BitSlider component demo page
This issue is based on issue #278

### PR DESCRIPTION
**Pull request by RezaKargar**
This resolves #711 by adding demo page for `BitSlider`
component on playground and also updates the navigation menu to
add link for new demo page

### CODE REVIEW

**Comment by msynk** [comment]
It seems your IDE ignored the ".editorconfig" file or something because there are a lot of "Tab" characters that exist in the files you pushed which is not acceptable. please review this problem and fix it.
tnx.

**Comment by RezaKargar** [comment]
> It seems your IDE ignored the ".editorconfig" file or something because there are a lot of "Tab" characters that exist in the files you pushed which is not acceptable. please review this problem and fix it.
> tnx.

I've checked the file both github's file view and in my local file, I did not see any problem.
Please recheck and if the problem remains provide me more information to fix it,
Thanks a lot.

**Comment by msynk** [comment]
this how I see the codes:
image

**Comment by RezaKargar** [comment]
Oh, You are seeing the file like this because you are looking to the file from the review page

Please check file's actual content which can be find [here](https://github.com/bitfoundation/bitframework/blob/01c7051bf2fe6c3cd3737a324d775d88767dc9e7/src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/Sliders/BitSliderDemo.razor)
Best regards

**Comment by msynk** [comment]
It's clear that there is a lot of "Tab" characters in the file. I mean the "\t". you could simply test it when you select the empty spaces between characters.
the review page shows the character correctly this way :)

**Comment by msynk** [comment]
Since the BitSlider component is under a heavy refactor and improvement, this PR is not valid anymore.
So I'm closing it.

**Pull request closed without merging**
