### PR TITLE
Rename DividerAs prop of BreadCrumb to DividerIcon (#1833)

### LINKED ISSUE #1833: Rename the `DividerAs` parameter to `DividerIcon` in the BitBreadCrumb component
It's better to rename the `DividerAs` parameter in the BitBreadCrumb component. It is not clear what this parameter does this way.
A better name for this parameter could be `DividerIcon`.

### PR DESCRIPTION
**Pull request by RezaKargar**
This closes #1833

### CODE REVIEW

**Comment by msynk** [comment]
This PR will conflict with PR #1830 which is adding tests for this component.
so I'm pending this PR for now.

**Comment by msynk** [comment]
since PR #1830  is merged now, I'm removing the pending.

**Comment by msynk** [comment]
@RezaKargar any updates?

**Comment by RezaKargar** [comment]
Not yet,
I'll work on it in about 2 days

**Review by msynk — APPROVED** [review]

**Pull request merged**
