### PR TITLE
fix dto's validation and write error message's

### PR DESCRIPTION
**Pull request by MohammadJavadTabari**
based on latest issue for todo template

### CODE REVIEW

**Comment by msynk** [comment]
@MohammadJavadTabari 
tnx a lot for your PR, but there are several things that are wrong with your changes.

please read this article first about contributing to our open source projects (do not create pull requests directly from your fork's develop branch):
https://www.dataschool.io/how-to-contribute-on-github/

and also we need to have a specific issue submitted for each PR. please review other PRs to grasp the general idea.

**Comment by MohammadJavadTabari** [comment]
ok . so I create new branch on my fork and call it "editForms_validation"  . then I should  make changes . then push it on my fork . then create PR  in upstream  repo for "editForms_validation" . Am I right?

**Comment by msynk** [comment]
@MohammadJavadTabari 
what is the issue you're working on? (what is its number?)
did you check other PRs and see what we need to have in a valid PR? (for example, how to name a branch, how the PR's title should be, what should be in a PR's description)

**Comment by MohammadJavadTabari** [comment]
seems the issue is resolved by some one else .
yeah I see other PR's and find out what to do and how is naming a PR there and again yes I also see branch naming .
sorry for this mistake . I do my best in other issue's .

**Comment by msynk** [comment]
since this PR is not relevant anymore, I'm closing it.

**Pull request closed without merging**
