### PR TITLE
Fix icon page render issue (#1861)

### LINKED ISSUE #1861: Render issues of the `Iconography` page in the BitBlazorUI demo project
The icon page renders with delay. This delay is probably because of the number of icons rendered on this page.

### PR DESCRIPTION
**Pull request by sajadkardel**
this closes #1861

### CODE REVIEW

**Comment by msynk** [comment]
@maryamhdr & @Cyrus-Sushiant plz review this PR

**Comment by msynk** [comment]
@ysmoradi could you please check if the slowness issue is resolved with this PR?

**Comment by ysmoradi** [comment]
> @ysmoradi could you please check if the slowness issue is resolved with this PR?

Sure, I'm on it

**Comment by ysmoradi** [comment]
It opens without hanging due to the fact that we're using virtualization at the moment.
But when I scroll up or down, items react weirdly! /-:

image
Then I scroll down a little
image

If this is a hard to solve problem, then ignore it, but if not, let's fix it.

**Comment by msynk** [comment]
There is an issue in the Virtualize component that is used in the BitBasicList component, which is not going to be addressed soon based on the conversation in this Github issue:
https://github.com/dotnet/aspnetcore/issues/28821

**Comment by maryamhdr** [comment]
> There is an issue in the Virtualize component that is used in the BitBasicList component, and it seems it is not going to be addressed soon based on the conversation in this Github issue: [dotnet/aspnetcore#28821](https://github.com/dotnet/aspnetcore/issues/28821) this requested feature is what we actually need for resolving this issue. so we need to think about other solutions.

So let's talk about it :)

**Comment by msynk** [comment]
Since we decided to apply another approach to resolve this issue, I'm closing this PR.

**Pull request closed without merging**
