### PR TITLE
improve the API of the message box of the todo template(#1943)

### PR DESCRIPTION
**Pull request by MohammadJavadTabari**
it's my first experience in bit 'components', I just add "Close Icon, Button Style, Button Class, and Button Type" for now. I want to add "Position" to the "Message Box" in the next update and maybe some "custom icon" and "Class" to "Message Box Body". also "Timer" for "Message Box"

### CODE REVIEW

**Comment by msynk** [comment]
@MohammadJavadTabari 
thank you for your efforts, but please do not start to work on any issues that come to your mind.
ask about the issue before starting or pick an issue that has an `up for grabs` label.
this PR is not good enough for the issue, so I'm closing it.

**Comment by MohammadJavadTabari** [comment]
@msynk 
ok tnx, but I was still working on it, it was not complete yet at all. so, please can you explain more about my mistakes. so I do not repeat them?

**Comment by msynk** [comment]
This issue is a little big for you in this state.
I need to take care of it myself. so it's not something that you did wrong in it specifically.

**Comment by MohammadJavadTabari** [comment]
> This issue is a little big for you in this state. I need to take care of it myself. so it's not something that you did wrong in it specifically.

ok, got it. tnx for guidance.

**Pull request closed without merging**
